# Generated by Django 4.0.4 on 2022-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_smart',
            field=models.BooleanField(default=False),
        ),
    ]
