version: '3.7'

services:
  server:
    restart: always
    container_name: backend
    image: ${GITLAB_REGISTRY}/server:${TAG}
    command: bash -c 'python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000'
    # env_file:
    #   - ./server/settings.ini
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  client:
    restart: always
    container_name: frontend
    image: ${GITLAB_REGISTRY}/client:${TAG}
    command : npm start
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true