/**
 * makes a GET request to classify an image in an existing/uploaded ebook
 * @param {String} ebookUuid: UUID of ebook under edit, generated by server upon upload
 * @param {String} filename: filename of classified image
 * @returns  response by server
 */
 export function getImageMetadataApiCall(ebookUuid, filename) {
    return fetch(
        process.env.REACT_APP_API_URL + 'images/get/' + filename + '/',
        {
            method: 'GET',
            headers: { 'Content-Type': 'application/json; charset=UTF-8', 'ebook': ebookUuid },
        }
    )
        .then((response) => {
            if (response.ok) {
                console.log(response.status)
                console.log(response.body)
                return response.json()
            }
            throw new Error('Response code: ' + response.status)
        })
        .then((response) => response)
        .catch((error) => {
            throw error
        })
           
}
