import PropTypes from 'prop-types'
import { getFile } from '../api/DownloadFile'
import styles from './FileDownload.module.scss'

/**
 * The FileDownload component provides the user with a button
 * that lets them download (export) the finished epub file.
 * 
 * @param {String} ebookId The UUID of e-book generated by server
 * @component
 * @returns element containing download button
 */
function FileDownload({ ebookId }) {
    return (
        <div id="container" className={styles.container}>
            <div className={styles.popup}>Download annotated ePub file</div>
            <button type="button" onClick={() => getFile(ebookId)}>
                Download e-book
            </button>
        </div>
    )
}

FileDownload.propTypes = {
    /**
     * String UUID of e-book generated by server
     */
    ebookId: PropTypes.string.isRequired,
}

export default FileDownload
