import PropTypes from 'prop-types'
import { getFile } from '../api/DownloadFile'
import styles from './FileDownload.module.scss'

/**
 * adds element that handles download process
 * @param {{ebookId: UUID of e-book generated by server}} props The props of the component
 * @returns element containing download button
 */
function FileDownload({ ebookId }) {
    return (
        <div id="container" className={styles.container}>
            <div className={styles.popup}>Download annotated ePub file</div>
            <button type="button" onClick={() => getFile(ebookId)}>
                Download
            </button>
        </div>
    )
}

FileDownload.propTypes = {
    ebookId: PropTypes.string.isRequired,
}

export default FileDownload
